
solitary_data <- read.csv("aslo_solitary.csv",row.names = 1)
fraser_data <- read.csv("aslo_fraser.csv",row.names=1)
solitary_NMDS=metaMDS(solitary_data,k=2,trymax=100)
fraser_NMDS=metaMDS(fraser_data,k=2,trymax=100)
stressplot(solitary_NMDS)
stressplot(fraser_NMDS)
#plot(solitary_NMDS)
ordiplot(fraser_NMDS,type="n")
orditorp(fraser_NMDS,display="species",col=c(rep("green",7),rep("blue",7)),air=0.01)
#orditorp(solitary_NMDS,display="sites",cex=1.25,air=0.01)
#ordiplot(fraser_NMDS,type="n")
#orditorp(fraser_NMDS,display="species",col=c(rep("green",7),rep("blue",7)),air=0.01)
ordicluster(fraser_NMDS,hclust(vegdist(community_matrix,"bray"))) 